### ISSUE TITLE
set up poetry!

### ISSUE THREAD

**Issue by t-valentine** [t-valentine/cis245-testbank#2]

**Comment by NiteToad** [comment]
I have set up poetry and provided some documentation in README.md. 

Once you clone or pulled the latest git, you can type in your terminal `poetry install` to have it installed. Then to make sure you are utilizing the poetry environment for your code you type in terminal `poetry shell`.

**Comment by NiteToad** [comment]
Once everyone has this repo on their machine and ran through the poetry set up, we can declare this issue/story done. Everyone can comment leave a comment stating it is done or give this comment a reaction of a thumbs up.

**Comment by NiteToad** [comment]
I have updated the README.md to include further instructions on setting up poetry on your pc. If you don't have poetry already on your pc you will need to install from their website [poetry](https://python-poetry.org/docs/#installation). Below are the steps in case you don't want to visit the website, and some of the steps are on the README.md as well.

**Step 1. Install Poetry**

Linux, macOS, Windows (WSL):
`curl -sSL https://install.python-poetry.org | python3 -`

Windows (Powershell):
`(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -`

**Step 2. Add Poetry to your PATH**

After installing poetry may add complete this task for or not. Regardless after the installation you will see a message in your terminal of how to add poetry to your PATH.
However here are some examples of how it may look like.

Windows (Powershell):
`$env:PATH += ";$env:USERPROFILE\.local\bin"`

Mac OS (zsh):
`export PATH="$HOME/.local/bin:$PATH"`
`source ~/.zshrc`

Linux:
`echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc`
`source ~/.bashrc`

**Step 3. Use poetry**

Once poetry is installed and added to your $PATH, you should be able to run the following:

`poetry --version`

If this works now you can change into your repository directory and run `poetry install`.

**Comment by Bertelib** [comment]
I am still struggling with Poetry in  my file does not have the element pipoetry.toml
